server:
  port: 8085
energy:
  port: 18085
spring:
  #  数据源配置
  datasource:
    druid:
      url: jdbc:mysql://192.168.31.201:3306/electric?useSSL=false
      username: root
      password: LDaf-2022
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    cluster:
      nodes: 192.168.31.201:6379,192.168.31.202:6379,192.168.31.203:6379
    database: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

logging:
  level:
    com.awen: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS