server:
  port: 8084

spring:
  application:
    name: shiro
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.31.201:3306/cloud_verify?useSSL=false
      username: root
      password: LDaf-2022
  redis:
    cluster:
      nodes: 192.168.31.201:6379,192.168.31.202:6379,192.168.31.203:6379
    database: 0
    jedis:
      pool:
        max-wait: 1ms
        max-active: 8
        max-idle: 8
        min-idle: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

logging:
  level:
    com.awen: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

jwtProperties:
  SecretKey: zngjngsoft2022
  Salt: zngjng